### ISSUE TITLE
maybe add `dev` branch and maintain stable `master`?

### ISSUE THREAD

**Issue by srigsby** [IntrepidPig/orca#1]
tried to point to this repo instead of the version on crates.io  
![screen shot 2018-02-06 at 5 06 41 am](https://user-images.githubusercontent.com/1192684/35861359-441c5e28-0afc-11e8-9c9c-10bd56266024.png)  

probably not highest priority, but it would be cool if master could be relied on (could autodeploy dev changes to master if they compile/pass test suite)

-rust noob
so maybe there is just a flag i can add to ignore `#![feature` compilation problem
and generally very open to being wrong//ignored here :)

**Comment by IntrepidPig** [comment]
Whoops. I don't think that feature flag is even necessary anymore. I'll be able to fix it later today.

I think a dev branch is a good idea, especially since this project is often lagging behind a fair bit on crates.io. I plan to publish version 0.5.0 as soon as it's been more thoroughly tested, I add some examples, and a little more of the most basic API functionality is implemented.

**Comment by IntrepidPig** [comment]
All right, I've added a dev branch now. I had to figure out how git branches work, but it turns out it's pretty simple, and I really like the workflow. I think this issue can be closed now. Thanks for participating in my project!
