### ISSUE TITLE
last example in readme doesn't seem right

### ISSUE THREAD

**Issue by srigsby** [IntrepidPig/orca#5]
concerning: [Example: Authorizing as OAuth Script type](https://github.com/IntrepidPig/orca#example-authorizing-as-oauth-script-type)

after a bit of fussing I managed to get the following to work:  
```rust
use orca::App;
use orca::net::auth::OAuthApp; 
fn main () {
    let mut reddit = App::new(name, version, author).unwrap();
    reddit.authorize(OAuthApp::Script {
    	id: app_id,
    	secret: app_secret, 
    	username: username,
    	password: password
    }).unwrap();
    println!("{:?}", reddit.get_self());
}
```

- is first line in example code supposed to instead be `let mut reddit` instead of the current `let mut app`? (this one i think is at least straightforward)
- not sure what the deal is with the fields (`id:, secret:, username:`) having to be named, might just be me and the weird way I'm accessing it.

**Comment by IntrepidPig** [comment]
You are correct that example in the readme is way out of date. At some point, I changed the enum from a tuple variant to a struct variant, which has the named fields. I'll update the readme, but for future reference, until the project hits 1.0, the best place to see usage examples is the tests and examples folder since I'll be checking that those compile before every merge to master. Of course the readme should be reputable as well, but it's much more likely I'll forget to check that those examples compile.

Now that this has been brought to my attention though, I'm thinking of changing the way authorization is implemented. I'm considering two different options right now
 * Option one is to create methods `authorize_script()`, `authorized_installed_app()`, and eventually `authorize_web()`, with specialized arguments for each, and remove the `OAuthApp` enum in favor of using those methods directly. Part of the reason I want to do this is to eliminate the weirdness of having both a `enum OAuthApp` and an `enum OAuth`.
* Option two is to create an `trait Auth`, and make a `struct Script`, `struct InstalledApp`, and `struct WebApp` that implement `Auth`. I'm not exactly sure what would be necessary in the `Auth` trait though. The only real advantage to this method is the user could implement their own `Auth`, but once I implement web app authentication, that shouldn't be necessary. Besides, I don't think it will be worth it to start dealing with a bunch of trait objects which wil recquire a ton of refactoring. I'll be working on option one for now, unless I find a compelling reason to do option two instead in the process. I'll open a new issue as a tracker for my progress on switching to the new auth system.
